version: '3'

dotenv: ['.env']
env:
  REPO_UPLOAD_FUNCTION: "{{.ACCOUNT_ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/photup/upload-image-function"
  REPO_LIST_FUNCTION: "{{.ACCOUNT_ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/photup/list-image-function"

tasks:
  deploy:
    desc: Build and Deploy the SAM application
    cmds:
      - sam build
      - |
        sam deploy \
        --image-repositories "UploadImageFunction=${REPO_UPLOAD_FUNCTION}" \
        --image-repositories "ListImageFunction=${REPO_LIST_FUNCTION}"
  sync:
    desc: Sync the SAM application with the latest changes
    cmds:
      - | 
        sam sync \
        --image-repositories "UploadImageFunction=${REPO_UPLOAD_FUNCTION}" \
        --image-repositories "ListImageFunction=${REPO_LIST_FUNCTION}"
